# Generated by Django 4.0 on 2022-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailwayApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fromAddress', models.CharField(max_length=100)),
                ('toAddress', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rail',
            },
        ),
    ]
